### ISSUE TITLE
segfault in tools_select::StructureSelector::finalize()

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#230]
```
#include <vinecopulib.hpp>

int main()
{
    Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> mtx(1,12);
    mtx << 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1;
    vinecopulib::Vinecop vine(mtx);
}
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7617cdd in vinecopulib::tools_select::StructureSelector::finalize (this=0x7fffffffdb50) at /home/vagrant/devel/vinecopulib/src/vinecop/tools_select.cpp:313
313                 mat(t, col) = trees_[t][e0].conditioned[0];
(gdb) bt
#0  0x00007ffff7617cdd in vinecopulib::tools_select::StructureSelector::finalize (this=0x7fffffffdb50) at /home/vagrant/devel/vinecopulib/src/vinecop/tools_select.cpp:313
#1  0x00007ffff7616506 in vinecopulib::tools_select::VinecopSelector::select_all_trees (this=0x7fffffffdb50, data=...) at /home/vagrant/devel/vinecopulib/src/vinecop/tools_select.cpp:103
#2  0x00007ffff75ee034 in vinecopulib::Vinecop::select_all (this=0x7fffffffdf10, data=..., controls=...) at /home/vagrant/devel/vinecopulib/src/vinecop/class.cpp:241
#3  0x00007ffff75ed7db in vinecopulib::Vinecop::Vinecop (this=0x7fffffffdf10, data=..., controls=...) at /home/vagrant/devel/vinecopulib/src/vinecop/class.cpp:160
#4  0x000000000040233b in main () at aqq.cpp:7
```

**Comment by tvatter** [comment]
See #251
